### ISSUE TITLE
AuthTokens?

### ISSUE THREAD

**Issue by Halama** [keboola/app-gooddata-writer-migrate#2]
Vypadá to že v EU to založí default writer jako production a v US jako demo.

**Comment by Halama** [comment]
@JakubMatejka Jak je to prosím s těmi auth tokeny?
To co to vrací a je tam možné zadat jsou nějaké naše aliasy? Vidím `keboola_demo` a `keboola_production`.

https://keboolagooddatawriterv2.docs.apiary.io/#reference/writers/writers/create-writer-with-empty-project

Můžu ten auth token teda také přebírat a předávat ho při založení? Zatím ho tam nedávám a zakládá to v EU prod projekty https://github.com/keboola/app-gooddata-writer-migrate/blob/b2aadc4b4b4181f7729c35c6b03df40663d03c4b/src/GoodDataWriterMigrate.php#L149

Což je ale možná ok možná bysme demo ani nemuseli migrovat.

![image](https://user-images.githubusercontent.com/903531/40166988-271e6c72-59c0-11e8-97f2-d13e82e71a45.png)

**Comment by Halama** [comment]
asi to tak bude
https://github.com/keboola/kbc-ui/blob/96cec9d272e5fc200846c80c06a00eb8a134b4fa/src/scripts/modules/components/Constants.coffee#L150

**Comment by JakubMatejka** [comment]
Jo, přesně tak. Default je tuším produkce a `keboola_production`, `production_demo` jsou placeholdery našich tokenů. Jinak tam můžeš zadat svůj token, když máš.

**Comment by Halama** [comment]
ok super dík, udělám to asi tak že budeme migrovat jenom writery které mají `keboola_production`, nebo `keboola_demo` token. U ostatních to řekne že je to skipnulo.

**Comment by JakubMatejka** [comment]
Ještě je tam vlastně náš Vertica token (je stejný jako produkční, ale v suffixu je `_VERTICA`). Ten ale nemá placeholder. Možná by bylo lepší se pro jistotu zeptat Padáka, jestli těch našich náhodou není ještě víc.


--
Jakub Matějka
Developer | Keboola Brno
www.keboola.com

**Comment by Halama** [comment]
ok, to ověřím zatím to migruje vše 1:1. Zařve to když se posílá špatný token?

**Comment by JakubMatejka** [comment]
Jo, vytvoření projektu v GD vyfailuje

**Comment by Halama** [comment]
V EU používáme jenom naše dva tokeny. V US je jich víc https://connection.keboola.com/admin/projects/258/transformations/bucket/392932549/transformation/394234460

**Comment by Halama** [comment]
https://keboola.slack.com/archives/C02CGRFK2/p1526643966000003

**Comment by Halama** [comment]
Jinak si bych to potom upravil takhle pokud padák nepřijde s něčím jiným:
- `keboola_vertica` se migruje na `keboola_production`
- možnost zadat do parametrů custom token který se nastaví všem migrovaným projektům

**Comment by Halama** [comment]
vertica token hází všude 500 hodil jsem na supprot https://support.gooddata.com/hc/en-us/requests/81346
https://connection.keboola.com/admin/projects/4788/jobs/394253006?q=
https://connection.eu-central-1.keboola.com/admin/projects/168/jobs/1671590?q=

**Comment by Halama** [comment]
pokračuje v #7
